name: 'Get hash of last successful job'
description: 'Finds the commit hash of the most recent successful conclusion of a job'
author: 'laurence79'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  job:
    description: 'The id of the job (defaults to current)'
    required: false
  owner:
    description: 'The owner of the repo (defaults to current)'
    required: false
  repo:
    description: 'The repo (defaults to current)'
    required: false
  workflow:
    description: 'The filename of the workflow, or the workflow id (defaults to current)'
    required: false
  github_token:
    description: 'The token to use with the GitHub API'
    required: false

# Define your outputs here.
outputs:
  commit_sha:
    description: 'The commit SHA of the run'
  run_id:
    description: 'The run ID containing the successful job'

runs:
  using: node20
  main: dist/index.js
