name: Semantic release
on:
  push:
    branches:
      - main

jobs:
  semantic_release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: npm

    - name: Dependencies
      run: |
        npm ci

    - name: Build
      run: |
        npm run all
        
    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v3
      with:
        extra_plugins: |
          @semantic-release/npm@9
          @semantic-release/changelog
          @semantic-release/exec
          @semantic-release/git
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}